In [1]:
import pandas as pd

In [3]:
na_df = pd.read_csv("C:/Users/jsuri/Downloads/H_A/north_america_dataset.csv")

In [5]:
# Get total rows and calculate split size
total_rows = len(na_df)  # 1,000,414 rows
split_size = total_rows // 2  # 500,207 rows per file

In [9]:
# Split into two parts
na_df_part1 = na_df.iloc[:split_size]  # First 500,207 rows
na_df_part2 = na_df.iloc[split_size:]  # Remaining 500,207 rows

In [23]:
na_df_part1.head()

,ID,Age_Group,Gender,Region_Category,Smoking_Status,Alcohol_Consumption,Diet_Quality,Cholesterol_Level,Blood_Pressure,BMI,Physical_Activity,Stress_Level,Diabetes,Air_Quality_Index,Income_Level,Sleep_Hours,Heart_Rate,Medication_Status,Heart_Attack
0,1,Youth,Female,United States,Current Smoker,Moderate,Average,219,130,24.0,Moderate,High,No Diabetes,Moderate,High,4.3,98,Not on Medication,No Heart Attack
1,2,Adult,Female,United States,Non-smoker,Moderate,Average,151,122,35.6,Good,Moderate,Has Diabetes,Good,Medium,8.0,81,Not on Medication,No Heart Attack
2,3,Adult,Male,United States,Former Smoker,Moderate,Average,141,155,22.3,Moderate,High,No Diabetes,Good,Low,5.9,84,Not on Medication,Heart Attack Occurred
3,4,Youth,Other,United States,Former Smoker,Moderate,Average,122,98,27.0,Moderate,Low,No Diabetes,Moderate,Medium,9.7,77,Not on Medication,No Heart Attack
4,5,Youth,Male,United States,Non-smoker,Moderate,Poor,251,174,37.6,Good,Low,No Diabetes,Good,Low,8.9,70,Not on Medication,No Heart Attack

In [17]:
na_df_part1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500207 entries, 0 to 500206
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   500207 non-null  int64
 1   Age_Group            500207 non-null  object
 2   Gender               500207 non-null  object
 3   Region_Category      500207 non-null  object
 4   Smoking_Status       500207 non-null  object
 5   Alcohol_Consumption  500207 non-null  object
 6   Diet_Quality         500207 non-null  object
 7   Cholesterol_Level    500207 non-null  int64
 8   Blood_Pressure       500207 non-null  int64
 9   BMI                  500207 non-null  float64
 10  Physical_Activity    500207 non-null  object
 11  Stress_Level         500207 non-null  object
 12  Diabetes             500207 non-null  object
 13  Air_Quality_Index    500207 non-null  object
 14  Income_Level         500207 non-null  object
 15  Sleep_Hours          500207 non-null  float64
 16  Heart_Rate           500207 non-null  int64
 17  Medication_Status    500207 non-null  object
 18  Heart_Attack         500207 non-null  object
dtypes: float64(2), int64(4), object(13)
memory usage: 72.5+ MB

In [19]:
na_df_part2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500207 entries, 500207 to 1000413
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   500207 non-null  int64
 1   Age_Group            500207 non-null  object
 2   Gender               500207 non-null  object
 3   Region_Category      500207 non-null  object
 4   Smoking_Status       500207 non-null  object
 5   Alcohol_Consumption  500207 non-null  object
 6   Diet_Quality         500207 non-null  object
 7   Cholesterol_Level    500207 non-null  int64
 8   Blood_Pressure       500207 non-null  int64
 9   BMI                  500207 non-null  float64
 10  Physical_Activity    500207 non-null  object
 11  Stress_Level         500207 non-null  object
 12  Diabetes             500207 non-null  object
 13  Air_Quality_Index    500207 non-null  object
 14  Income_Level         500207 non-null  object
 15  Sleep_Hours          500207 non-null  float64
 16  Heart_Rate           500207 non-null  int64
 17  Medication_Status    500207 non-null  object
 18  Heart_Attack         500207 non-null  object
dtypes: float64(2), int64(4), object(13)
memory usage: 72.5+ MB

In [21]:
na_df_part2.head()

,ID,Age_Group,Gender,Region_Category,Smoking_Status,Alcohol_Consumption,Diet_Quality,Cholesterol_Level,Blood_Pressure,BMI,Physical_Activity,Stress_Level,Diabetes,Air_Quality_Index,Income_Level,Sleep_Hours,Heart_Rate,Medication_Status,Heart_Attack
500207,500208,Adult,Female,Canada,Non-smoker,Moderate,Poor,159,91,36.4,Good,Moderate,No Diabetes,Moderate,Medium,5.0,99,Not on Medication,No Heart Attack
500208,500209,Adult,Male,United States,Former Smoker,Moderate,Poor,144,144,20.3,Moderate,Moderate,No Diabetes,Good,Low,6.7,73,Not on Medication,No Heart Attack
500209,500210,Adult,Male,United States,Current Smoker,Moderate,Average,289,172,27.0,Good,Moderate,No Diabetes,Good,High,8.3,53,Not on Medication,No Heart Attack
500210,500211,Adult,Male,United States,Non-smoker,Moderate,Excellent,151,157,30.8,Bad,Low,No Diabetes,Good,Medium,8.3,76,Not on Medication,No Heart Attack
500211,500212,Youth,Female,United States,Non-smoker,Moderate,Average,152,149,22.7,Good,Moderate,No Diabetes,Moderate,Low,7.6,97,Not on Medication,No Heart Attack

In [25]:
na_df_part1.to_csv("C:/Users/jsuri/Downloads/H_A/north_america_part_1.csv", index=False)

In [27]:
na_df_part2.to_csv("C:/Users/jsuri/Downloads/H_A/north_america_part_2.csv", index=False)